# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint1:
    has_position_limits: true
    min_position: -6.28319
    max_position: 6.28319
    has_velocity_limits: true
    max_velocity: 4.8868
    has_acceleration_limits: true
    max_acceleration: 4.88692
  joint2:
    has_position_limits: true
    min_position: -6.28319
    max_position: 6.28319
    has_velocity_limits: true
    max_velocity: 4.8868
    has_acceleration_limits: true
    max_acceleration: 4.88692
  joint3:
    has_position_limits: true
    min_position: -6.28319
    max_position: 6.28319
    has_velocity_limits: true
    max_velocity: 4.8868
    has_acceleration_limits: true
    max_acceleration: 4.88692
  joint4:
    has_position_limits: true
    min_position: -6.28319
    max_position: 6.28319
    has_velocity_limits: true
    max_velocity: 4.8868
    has_acceleration_limits: true
    max_acceleration: 4.88692
  joint5:
    has_position_limits: true
    min_position: -6.28319
    max_position: 6.28319
    has_velocity_limits: true
    max_velocity: 4.8868
    has_acceleration_limits: true
    max_acceleration: 4.88692
  joint6:
    has_position_limits: true
    min_position: -6.28319
    max_position: 6.28319
    has_velocity_limits: true
    max_velocity: 4.8868
    has_acceleration_limits: true
    max_acceleration: 4.88692